import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
    selector: 'app-input-button-unit',
    templateUrl: './input-button-unit.component.html',
    styleUrls: [ './input-button-unit.component.scss' ]
})
export class InputButtonUnitComponent implements OnInit {
    @Output() submit: EventEmitter<string> = new EventEmitter();
    title = '';

    constructor() {
    }

    ngOnInit() {
        // let inputElement = document.getElementById('my-input');
        //
        //
        // setTimeout(() => {
        //     this.title = 'This is not the title you are looking for';
        //     inputElement.title = this.title;
        //
        // }, 3000);
    }

    submitValue(title) {
        this.submit.emit(title);
    }

    // generateTitle(): string {
    //     return 'This title was generated by a method.';
    // }

}
